<h1>100 numpy exercises </h1>

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configurationB

In [3]:
print(np.__version__)
np.show_config()

2.0.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

3. Create a null vector of size 10

In [6]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array 

In [7]:
size = null_vector.size * null_vector.itemsize
size

80

5. How to get the documentation of the numpy add function from the command line?

In [8]:
print(np.info(np.ndim))

Return the number of dimensions of an array.

Parameters
----------
a : array_like
    Input array.  If it is not already an ndarray, a conversion is
    attempted.

Returns
-------
number_of_dimensions : int
    The number of dimensions in `a`.  Scalars are zero-dimensional.

See Also
--------
ndarray.ndim : equivalent method
shape : dimensions of array
ndarray.shape : dimensions of array

Examples
--------
>>> np.ndim([[1,2,3],[4,5,6]])
2
>>> np.ndim(np.array([[1,2,3],[4,5,6]]))
2
>>> np.ndim(1)
0
None


6. Create a null vector of size 10 but the fifth value which is 1 

In [11]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 

In [14]:
np.set_printoptions(linewidth=130)  # Установка параметров печати.
#Параметры этого метода позволяют определить способы отображения чисел с плавающей запятой,
#массивов и других объектов NumPy.
#linewidth - кол-во знаков печати в ширину.
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [15]:
v = v[::-1]
v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20,
       19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 

In [16]:
v = np.arange(9).reshape(3, 3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from array [1,2,0,0,4,0]

In [19]:
v = np.array([1,2,0,0,4,0])
v_n = np.nonzero(v)
v_n

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix

In [21]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values 

In [23]:
v = np.random.randint(low=0 , high= 3,size=(3,3,3))
v

array([[[1, 2, 1],
        [2, 0, 0],
        [2, 2, 1]],

       [[1, 2, 0],
        [1, 1, 1],
        [0, 0, 2]],

       [[0, 2, 1],
        [1, 2, 2],
        [1, 1, 2]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
v = np.random.randint(low=0 , high= 100,size=(10, 10))
(np.max(v), np.min(v))

(np.int64(99), np.int64(1))

14. Create a random vector of size 30 and find the mean value

In [35]:
np.set_printoptions(suppress=True, precision=5, linewidth=50)
v = np.random.random(size=(100))
np.mean(v)

np.float64(0.5288582367825301)

15. Create a 2d array with 1 on the border and 0 inside