<h1> Basic of numpy <h1>

<a href='https://numpy.org/doc/stable/user/absolute_beginners.html'> numpy doc </a>

<h2> Атрибуты массива ndim, shape, size, dtype</h2>

In [19]:
import numpy as np

arr = np.array([1, 2, 3 , 4, 5])

print(arr.ndim, arr.shape, arr.dtype)

m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype='int8')

print(m.size, m.ndim, m.shape, m.dtype)

len(m.shape) == m.ndim

1 (5,) int64
12 2 (3, 4) int8


True

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


<h2> Создание базового массива np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace() </h2>

In [25]:
print(np.zeros(5, dtype='int8'))
print(np.ones(5, dtype='str'))

print(np.empty(5)) #Функция empty создает массив, начальное содержимое которого случайно и зависит от состояния памяти.

print(np.arange(2, 9, 2))

print(np.linspace(0, 10, num=5))

[0 0 0 0 0]
['1' '1' '1' '1' '1']
[1. 1. 1. 1. 1.]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


<h2> Добавление, удаление и сортировка элементов </h2>

In [26]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

<h2>Как преобразовать одномерный массив в двумерный (как добавить новую ось в массив)</h2>

Вы можете использовать np.newaxisи np.expand_dimsдля увеличения размеров существующего массива.

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape # (6, )
a2 = a[np.newaxis, :]
a2.shape # (1, 6)
a

array([1, 2, 3, 4, 5, 6])

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape # (6, )
b = np.expand_dims(a, axis=1)
b.shape #(6, 1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

<h2>Индексация и нарезка</h2>

In [36]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


<h2>Как создать массив из существующих данных</h2>

In [37]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [38]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [43]:
x = np.arange(1, 25).reshape(4, 6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [44]:
np.hsplit(x, 3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

<h2>Базовые операции с массивами</h2>

In [47]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)
print(data - ones)
print(data * data)
print(data / data)

[2 3]
[0 1]
[1 4]
[1. 1.]


In [48]:
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [49]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [51]:
b.sum(axis=1)

array([2, 4])

<h2>Трансляция</h2>

In [52]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [56]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data * 2 #любые операции

array([[0, 2, 2],
       [0, 0, 2]])

<h2>Генерация случайных чисел</h2>

In [59]:
rng = np.random.default_rng()
rng.integers(100, size=(2, 4)) 

array([[ 7, 21, 14, 73],
       [44, 32, 90,  6]])

<h2>Как получить уникальные предметы и количество </h2>

In [60]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True) #для получения индексов уникальных элементов
print(indices_list)

<h2>Транспонирование и изменение формы матрицы</h2>

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)

[8 7 6 5 4 3 2 1]


In [63]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [64]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [65]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


<h2>Изменение формы и выравнивание многомерных массивов</h2>

In [66]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()  # flatten отличается от ravel тем что ravel не создает копию родительского массива

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

<h2> Функции создания двумерного массива </h2>

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [70]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [71]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [72]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

<h2>Репликация, объединение или мутация существующих массивов</h2>

In [73]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [ ]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])
array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])