<h1>100 numpy exercises </h1>

<h2>1. Import the numpy package under the name np</h2>

In [1]:
import numpy as np

<h2>2. Print the numpy version and the configuration</h2>

In [2]:
print(np.__version__)
np.show_config()

2.0.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

<h2>3. Create a null vector of size 10</h2>

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<h2>4. How to find the memory size of any arra</h2> 

In [4]:
size = null_vector.size * null_vector.itemsize
size

80

<h2>5. How to get the documentation of the numpy add function from the command line?</h2>

In [5]:
print(np.info(np.ndim))

Return the number of dimensions of an array.

Parameters
----------
a : array_like
    Input array.  If it is not already an ndarray, a conversion is
    attempted.

Returns
-------
number_of_dimensions : int
    The number of dimensions in `a`.  Scalars are zero-dimensional.

See Also
--------
ndarray.ndim : equivalent method
shape : dimensions of array
ndarray.shape : dimensions of array

Examples
--------
>>> np.ndim([[1,2,3],[4,5,6]])
2
>>> np.ndim(np.array([[1,2,3],[4,5,6]]))
2
>>> np.ndim(1)
0
None


<h2>6. Create a null vector of size 10 but the fifth value which is 1</h2> 

In [6]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

<h2>7. Create a vector with values ranging from 10 to 49</h2>

In [7]:
np.set_printoptions(linewidth=130)  # Установка параметров печати.
#Параметры этого метода позволяют определить способы отображения чисел с плавающей запятой,
#массивов и других объектов NumPy.
#linewidth - кол-во знаков печати в ширину.
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

<h2>8. Reverse a vector (first element becomes last)</h2>

In [8]:
v = v[::-1]
v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20,
       19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

<h2>9. Create a 3x3 matrix with values ranging from 0 to 8 </h2>

In [9]:
v = np.arange(9).reshape(3, 3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h2>10. Find indices of non-zero elements from array [1,2,0,0,4,0]</h2>

In [10]:
v = np.array([1,2,0,0,4,0])
v_n = np.nonzero(v)
v_n

(array([0, 1, 4]),)

<h2>11. Create a 3x3 identity matrix</h2>

In [11]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h2>12. Create a 3x3x3 array with random values</h2>

In [12]:
v = np.random.randint(low=0 , high= 3,size=(3,3,3))
v

array([[[1, 0, 2],
        [0, 1, 1],
        [2, 0, 2]],

       [[2, 2, 2],
        [0, 2, 0],
        [0, 0, 1]],

       [[1, 2, 2],
        [1, 0, 0],
        [2, 2, 1]]])

<h2>13. Create a 10x10 array with random values and find the minimum and maximum values</h2>

In [13]:
v = np.random.randint(low=0 , high= 100,size=(10, 10))
(np.max(v), np.min(v))

(np.int64(99), np.int64(0))

<h2>14. Create a random vector of size 30 and find the mean value</h2>

In [14]:
np.set_printoptions(suppress=True, precision=5, linewidth=50)
v = np.random.random(size=(100))
np.mean(v)

np.float64(0.5125367131637497)

<h2>15. Create a 2d array with 1 on the border and 0 inside</h2>

In [15]:
m = np.ones((5, 5))
m[1:-1,1:-1] = 0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

<h2>16. How to add a border (filled with 0's) around an existing array?</h2>

In [16]:
v = np.ones((5,5))
v = np.pad(v, pad_width=1, mode='constant', constant_values=0)
v

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# если нужно отрезать (обнулить) от существующего массива
v = np.ones((5,5))
v[:, [0, -1]] = 0
v[[0, -1], :] = 0
v

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

<h2>17. What is the result of the following expression?</h2>

Каков результат следующих выражений ?

<div>0 * np.nan</div>
<div>np.nan == np.nan</div>
<div>np.inf > np.nan</div>
<div>np.nan - np.nan</div>
<div>np.nan in set([np.nan])</div>
<div>0.3 == 3 * 0.1</div>

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


<h2>18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal</h2>

In [19]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

<h2>19. Create a 8x8 matrix and fill it with a checkerboard pattern</h2>

In [20]:
m = np.zeros((8, 8), dtype='uint8')
m[1::2,::2] = 1
m[::2,1::2] = 1
m

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=uint8)

<h2>20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?</h2>

In [21]:
N = 100  # номер индекса (предполагаем, что счет элемментов начинается с 1 (единицы))
print(np.unravel_index(indices=N-1,shape=(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


<h2>21. Create a checkerboard 8x8 matrix using the tile function</h2>

In [22]:
m = np.array([[1,0], [0,1]])
np.tile(A=m, reps=(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

<h2>22. Normalize a 5x5 random matrix </h2>

In [23]:
np.set_printoptions(precision=4)
m = np.random.random((5,5))
print('Исходная матрица: \n', m)
print('Проверим, что матрица НЕ нормализованна по L1-норме: \n', np.sum(m, axis=1)[:, np.newaxis])

m_normilized = m / (np.sum(m, axis=1)[:, np.newaxis])
print('Нормализованная по L1-норме матрица m: \n', m_normilized)
print('Проверим, что матрица m нормализованна по L1-норме: \n', np.sum(m_normilized, axis=1)[:, np.newaxis])

Исходная матрица: 
 [[0.6938 0.1753 0.2448 0.1106 0.519 ]
 [0.7017 0.7779 0.8577 0.345  0.3405]
 [0.3993 0.6862 0.6758 0.2512 0.9287]
 [0.7018 0.8652 0.1126 0.6842 0.4076]
 [0.5627 0.7739 0.0879 0.4835 0.1384]]
Проверим, что матрица НЕ нормализованна по L1-норме: 
 [[1.7434]
 [3.0228]
 [2.9413]
 [2.7715]
 [2.0464]]
Нормализованная по L1-норме матрица m: 
 [[0.3979 0.1005 0.1404 0.0634 0.2977]
 [0.2321 0.2573 0.2837 0.1141 0.1126]
 [0.1358 0.2333 0.2298 0.0854 0.3157]
 [0.2532 0.3122 0.0406 0.2469 0.1471]
 [0.275  0.3782 0.043  0.2363 0.0676]]
Проверим, что матрица m нормализованна по L1-норме: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [24]:
# еще один способ нормализации c помощью метода linalg.norm
from numpy import linalg as LA
m_normilized2 = m/LA.norm(m, axis=1, ord=1)[:, np.newaxis]
print('Нормализованная по L1-норме матрица m c помощью метода linalg.norm: \n', m_normilized2)
print('Проверим, что полученные нормализованные матрицы одинаковы: \n', m_normilized2-m_normilized)

Нормализованная по L1-норме матрица m c помощью метода linalg.norm: 
 [[0.3979 0.1005 0.1404 0.0634 0.2977]
 [0.2321 0.2573 0.2837 0.1141 0.1126]
 [0.1358 0.2333 0.2298 0.0854 0.3157]
 [0.2532 0.3122 0.0406 0.2469 0.1471]
 [0.275  0.3782 0.043  0.2363 0.0676]]
Проверим, что полученные нормализованные матрицы одинаковы: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<h2>23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)</h2>

In [25]:
# в python в matplotlib значений RGBA это значения на отрезке от 0 до 1. Но при верстке сайтов 
color = np.dtype([('red', np.uint8),
                  ('green', np.uint8),
                  ('blue', np.uint8),
                  ('alpha', np.uint8)])
# инициализируем массив point с посмотрим на массив и на его тип
point = np.array([(0, 0, 0, 0), (255, 255, 255, 50)],dtype=color)
print('type of array point', type(point))
# выведем значения яркости трех цветов и прозрачности второй точки
point[1]
# на выходе получаем картеж
# выведем значения яркости красного цвета двух точек
point['red']
# на выходе получаем массив

type of array point <class 'numpy.ndarray'>


array([  0, 255], dtype=uint8)

<h2>24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) </h2>

In [26]:
m1 = np.random.randint(low=0 , high= 20, size=(5, 3))
m2 = np.random.randint(low=0 , high= 20, size=(3, 2))
m3 = m1 @ m2 # m3 = np.dot(m1, m2)
m3

array([[472, 443],
       [602, 622],
       [662, 597],
       [ 62,  60],
       [346, 359]])

<h2>25. Given a 1D array, negate all elements which are between 3 and 8, in place. </h2>

In [27]:
v = np.random.randint(low=0 , high= 12, size=(20))
v[(v <= 8) & (v >= 3)] *= -1
v

array([-6,  1,  1, 11,  0,  0, -6, 11, -3, 10,
       -7, -5,  1,  9, 10, -3,  2,  9, -5, -3])

<h2>26. What is the output of the following script?</h2>

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


<h2>27. Consider an integer vector Z, which of these expressions are legal?</h2>

In [29]:
v=np.arange(10)
print('Исходный вектор:\n',v, '\n')
print('v**v:\n', v**v, '\n')
print('2 << v >> 2:\n', 2 << v >> 2, '\n')
print('v <- v\n', v <- v, '\n')
print('1j*v\n', 1j*v, '\n')
print('v/1/1', v/1/1, '\n')

Исходный вектор:
 [0 1 2 3 4 5 6 7 8 9] 

v**v:
 [        1         1         4        27
       256      3125     46656    823543
  16777216 387420489] 

2 << v >> 2:
 [  0   1   2   4   8  16  32  64 128 256] 

v <- v
 [False False False False False False False False
 False False] 

1j*v
 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j
 0.+7.j 0.+8.j 0.+9.j] 

v/1/1 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 



In [30]:
try:
    print(v<v>v)
except Exception as err:
    print('при попытке выполнения v<v>v получаем ошибку выполнения:', err.__class__)

при попытке выполнения v<v>v получаем ошибку выполнения: <class 'ValueError'>


<h2>28. What are the result of the following expressions?</h2>

In [31]:
print('Результат выполнения np.array(0) / np.array(0):\n', np.array(0) / np.array(0), '\n')
print('Результат выполнения np.array(0) // np.array(0):\n', np.array(0) // np.array(0), '\n')
print('Результат выполнения np.array([np.nan]).astype(int).astype(float):\n', np.array([np.nan]).astype(int).astype(float), '\n')

Результат выполнения np.array(0) / np.array(0):
 nan 

Результат выполнения np.array(0) // np.array(0):
 0 

Результат выполнения np.array([np.nan]).astype(int).astype(float):
 [-9.2234e+18] 



/tmp/ipykernel_12215/2077636124.py:1: RuntimeWarning: invalid value encountered in divide
  print('Результат выполнения np.array(0) / np.array(0):\n', np.array(0) / np.array(0), '\n')
/tmp/ipykernel_12215/2077636124.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print('Результат выполнения np.array(0) // np.array(0):\n', np.array(0) // np.array(0), '\n')
/tmp/ipykernel_12215/2077636124.py:3: RuntimeWarning: invalid value encountered in cast
  print('Результат выполнения np.array([np.nan]).astype(int).astype(float):\n', np.array([np.nan]).astype(int).astype(float), '\n')


<h2>29. How to round away from zero a float array ?</h2>

In [34]:
# инициализируем симметричный относительно нуля вектор, по которому просто проверять округление
v = (np.arange(15)-7)/4
print('\n', v)
v_round1 = np.around(v,decimals=0)
print('Округленный стандартным методом np.around вектор:\n', v_round1)
v_round2 = np.round(v,decimals=0)
print('Округленный стандартным методом np.round вектор:\n', v_round2)


 [-1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.
  0.25  0.5   0.75  1.    1.25  1.5   1.75]
Округленный стандартным методом np.around вектор:
 [-2. -2. -1. -1. -1. -0. -0.  0.  0.  0.  1.  1.
  1.  2.  2.]
Округленный стандартным методом np.round вектор:
 [-2. -2. -1. -1. -1. -0. -0.  0.  0.  0.  1.  1.
  1.  2.  2.]


In [33]:
v_round_away1 = np.copysign(np.ceil(np.abs(v)), v)
print('Округленный ВВЕРХ вектор первым способом:\n', v_round_away1)
v_round_away2 = np.where(v>0, np.ceil(v), np.floor(v))
print('Округленный ВВЕРХ вектор v вторым способом:\n', v_round_away2)

Округленный ВВЕРХ вектор первым способом:
 [-2. -2. -2. -1. -1. -1. -1.  0.  1.  1.  1.  1.
  2.  2.  2.]
Округленный ВВЕРХ вектор v вторым способом:
 [-2. -2. -2. -1. -1. -1. -1.  0.  1.  1.  1.  1.
  2.  2.  2.]


<h2>30. How to find common values between two arrays?</h2>

In [36]:
v1 = np.random.randint(low=0 , high= 50, size=(20))
print(v1)
v2 = np.random.randint(low=0 , high= 50, size=(20))
print(v2)
print(intersect1d(v1, v2))

[22  3 41 46 46 22  8 25 27 21 39 47 37 24 30 24
 26 41  6  8]
[ 5 22 17 31 26 31 48  1 30 38 49  6 49 29 27  8
 28 10 34 32]
[ 6  8 22 26 27 30]
