<h1>100 numpy exercises </h1>

<h2>1. Import the numpy package under the name np</h2>

In [1]:
import numpy as np

<h2>2. Print the numpy version and the configuration</h2>

In [2]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd


<h2>3. Create a null vector of size 10</h2>

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<h2>4. How to find the memory size of any arra</h2> 

In [4]:
size = null_vector.size * null_vector.itemsize
size

80

<h2>5. How to get the documentation of the numpy add function from the command line?</h2>

In [5]:
print(np.info(np.ndim))

Return the number of dimensions of an array.

Parameters
----------
a : array_like
    Input array.  If it is not already an ndarray, a conversion is
    attempted.

Returns
-------
number_of_dimensions : int
    The number of dimensions in `a`.  Scalars are zero-dimensional.

See Also
--------
ndarray.ndim : equivalent method
shape : dimensions of array
ndarray.shape : dimensions of array

Examples
--------
>>> import numpy as np
>>> np.ndim([[1,2,3],[4,5,6]])
2
>>> np.ndim(np.array([[1,2,3],[4,5,6]]))
2
>>> np.ndim(1)
0
None


<h2>6. Create a null vector of size 10 but the fifth value which is 1</h2> 

In [6]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

<h2>7. Create a vector with values ranging from 10 to 49</h2>

In [7]:
np.set_printoptions(linewidth=130)  # Установка параметров печати.
#Параметры этого метода позволяют определить способы отображения чисел с плавающей запятой,
#массивов и других объектов NumPy.
#linewidth - кол-во знаков печати в ширину.
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

<h2>8. Reverse a vector (first element becomes last)</h2>

In [8]:
v = v[::-1]
v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20,
       19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

<h2>9. Create a 3x3 matrix with values ranging from 0 to 8 </h2>

In [9]:
v = np.arange(9).reshape(3, 3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h2>10. Find indices of non-zero elements from array [1,2,0,0,4,0]</h2>

In [10]:
v = np.array([1,2,0,0,4,0])
v_n = np.nonzero(v)
v_n

(array([0, 1, 4]),)

<h2>11. Create a 3x3 identity matrix</h2>

In [11]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h2>12. Create a 3x3x3 array with random values</h2>

In [12]:
v = np.random.randint(low=0 , high= 3,size=(3,3,3))
v

array([[[2, 2, 1],
        [0, 0, 2],
        [2, 1, 2]],

       [[1, 0, 1],
        [1, 0, 0],
        [1, 0, 2]],

       [[1, 2, 2],
        [2, 2, 2],
        [1, 2, 1]]])

<h2>13. Create a 10x10 array with random values and find the minimum and maximum values</h2>

In [13]:
v = np.random.randint(low=0 , high= 100,size=(10, 10))
(np.max(v), np.min(v))

(np.int64(99), np.int64(0))

<h2>14. Create a random vector of size 30 and find the mean value</h2>

In [14]:
np.set_printoptions(suppress=True, precision=5, linewidth=50)
v = np.random.random(size=(100))
np.mean(v)

np.float64(0.460785827267906)

<h2>15. Create a 2d array with 1 on the border and 0 inside</h2>

In [15]:
m = np.ones((5, 5))
m[1:-1,1:-1] = 0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

<h2>16. How to add a border (filled with 0's) around an existing array?</h2>

In [16]:
v = np.ones((5,5))
v = np.pad(v, pad_width=1, mode='constant', constant_values=0)
v

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# если нужно отрезать (обнулить) от существующего массива
v = np.ones((5,5))
v[:, [0, -1]] = 0
v[[0, -1], :] = 0
v

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

<h2>17. What is the result of the following expression?</h2>

Каков результат следующих выражений ?

<div>0 * np.nan</div>
<div>np.nan == np.nan</div>
<div>np.inf > np.nan</div>
<div>np.nan - np.nan</div>
<div>np.nan in set([np.nan])</div>
<div>0.3 == 3 * 0.1</div>

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


<h2>18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal</h2>

In [19]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

<h2>19. Create a 8x8 matrix and fill it with a checkerboard pattern</h2>

In [20]:
m = np.zeros((8, 8), dtype='uint8')
m[1::2,::2] = 1
m[::2,1::2] = 1
m

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=uint8)

<h2>20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?</h2>

In [21]:
N = 100  # номер индекса (предполагаем, что счет элемментов начинается с 1 (единицы))
print(np.unravel_index(indices=N-1,shape=(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


<h2>21. Create a checkerboard 8x8 matrix using the tile function</h2>

In [22]:
m = np.array([[1,0], [0,1]])
np.tile(A=m, reps=(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

<h2>22. Normalize a 5x5 random matrix </h2>

In [23]:
np.set_printoptions(precision=4)
m = np.random.random((5,5))
print('Исходная матрица: \n', m)
print('Проверим, что матрица НЕ нормализованна по L1-норме: \n', np.sum(m, axis=1)[:, np.newaxis])

m_normilized = m / (np.sum(m, axis=1)[:, np.newaxis])
print('Нормализованная по L1-норме матрица m: \n', m_normilized)
print('Проверим, что матрица m нормализованна по L1-норме: \n', np.sum(m_normilized, axis=1)[:, np.newaxis])

Исходная матрица: 
 [[0.2222 0.7908 0.019  0.9853 0.6943]
 [0.5822 0.5826 0.0568 0.7211 0.0347]
 [0.5963 0.2473 0.3878 0.3357 0.5511]
 [0.5239 0.5388 0.6301 0.5976 0.4142]
 [0.5197 0.5397 0.1717 0.6178 0.9172]]
Проверим, что матрица НЕ нормализованна по L1-норме: 
 [[2.7117]
 [1.9774]
 [2.1181]
 [2.7045]
 [2.7661]]
Нормализованная по L1-норме матрица m: 
 [[0.082  0.2916 0.007  0.3634 0.256 ]
 [0.2944 0.2946 0.0287 0.3647 0.0175]
 [0.2815 0.1168 0.1831 0.1585 0.2602]
 [0.1937 0.1992 0.233  0.2209 0.1532]
 [0.1879 0.1951 0.0621 0.2233 0.3316]]
Проверим, что матрица m нормализованна по L1-норме: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [24]:
# еще один способ нормализации c помощью метода linalg.norm
from numpy import linalg as LA
m_normilized2 = m/LA.norm(m, axis=1, ord=1)[:, np.newaxis]
print('Нормализованная по L1-норме матрица m c помощью метода linalg.norm: \n', m_normilized2)
print('Проверим, что полученные нормализованные матрицы одинаковы: \n', m_normilized2-m_normilized)

Нормализованная по L1-норме матрица m c помощью метода linalg.norm: 
 [[0.082  0.2916 0.007  0.3634 0.256 ]
 [0.2944 0.2946 0.0287 0.3647 0.0175]
 [0.2815 0.1168 0.1831 0.1585 0.2602]
 [0.1937 0.1992 0.233  0.2209 0.1532]
 [0.1879 0.1951 0.0621 0.2233 0.3316]]
Проверим, что полученные нормализованные матрицы одинаковы: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<h2>23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)</h2>

In [25]:
# в python в matplotlib значений RGBA это значения на отрезке от 0 до 1. Но при верстке сайтов 
color = np.dtype([('red', np.uint8),
                  ('green', np.uint8),
                  ('blue', np.uint8),
                  ('alpha', np.uint8)])
# инициализируем массив point с посмотрим на массив и на его тип
point = np.array([(0, 0, 0, 0), (255, 255, 255, 50)],dtype=color)
print('type of array point', type(point))
# выведем значения яркости трех цветов и прозрачности второй точки
point[1]
# на выходе получаем картеж
# выведем значения яркости красного цвета двух точек
point['red']
# на выходе получаем массив

type of array point <class 'numpy.ndarray'>


array([  0, 255], dtype=uint8)

<h2>24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) </h2>

In [26]:
m1 = np.random.randint(low=0 , high= 20, size=(5, 3))
m2 = np.random.randint(low=0 , high= 20, size=(3, 2))
m3 = m1 @ m2 # m3 = np.dot(m1, m2)
m3

array([[322, 293],
       [257, 205],
       [197, 267],
       [322, 160],
       [117,  90]])

<h2>25. Given a 1D array, negate all elements which are between 3 and 8, in place. </h2>

In [27]:
v = np.random.randint(low=0 , high= 12, size=(20))
v[(v <= 8) & (v >= 3)] *= -1
v

array([11, 11, 10, -3, -5, 11, 11, -7, -3, -8,
        2, -3, -5, -4, -8, -5, -8,  0, -3, -6])

<h2>26. What is the output of the following script?</h2>

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9


10


<h2>27. Consider an integer vector Z, which of these expressions are legal?</h2>

In [29]:
v=np.arange(10)
print('Исходный вектор:\n',v, '\n')
print('v**v:\n', v**v, '\n')
print('2 << v >> 2:\n', 2 << v >> 2, '\n')
print('v <- v\n', v <- v, '\n')
print('1j*v\n', 1j*v, '\n')
print('v/1/1', v/1/1, '\n')

Исходный вектор:
 [0 1 2 3 4 5 6 7 8 9] 

v**v:
 [        1         1         4        27
       256      3125     46656    823543
  16777216 387420489] 

2 << v >> 2:
 [  0   1   2   4   8  16  32  64 128 256] 

v <- v
 [False False False False False False False False
 False False] 

1j*v
 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j
 0.+7.j 0.+8.j 0.+9.j] 

v/1/1 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 



In [30]:
try:
    print(v<v>v)
except Exception as err:
    print('при попытке выполнения v<v>v получаем ошибку выполнения:', err.__class__)

при попытке выполнения v<v>v получаем ошибку выполнения: <class 'ValueError'>


<h2>28. What are the result of the following expressions?</h2>

In [31]:
print('Результат выполнения np.array(0) / np.array(0):\n', np.array(0) / np.array(0), '\n')
print('Результат выполнения np.array(0) // np.array(0):\n', np.array(0) // np.array(0), '\n')
print('Результат выполнения np.array([np.nan]).astype(int).astype(float):\n', np.array([np.nan]).astype(int).astype(float), '\n')

Результат выполнения np.array(0) / np.array(0):
 nan 

Результат выполнения np.array(0) // np.array(0):
 0 

Результат выполнения np.array([np.nan]).astype(int).astype(float):
 [-9.2234e+18] 



/tmp/ipykernel_9619/2077636124.py:1: RuntimeWarning: invalid value encountered in divide
  print('Результат выполнения np.array(0) / np.array(0):\n', np.array(0) / np.array(0), '\n')
/tmp/ipykernel_9619/2077636124.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print('Результат выполнения np.array(0) // np.array(0):\n', np.array(0) // np.array(0), '\n')
/tmp/ipykernel_9619/2077636124.py:3: RuntimeWarning: invalid value encountered in cast
  print('Результат выполнения np.array([np.nan]).astype(int).astype(float):\n', np.array([np.nan]).astype(int).astype(float), '\n')


<h2>29. How to round away from zero a float array ?</h2>

In [32]:
# инициализируем симметричный относительно нуля вектор, по которому просто проверять округление
v = (np.arange(15)-7)/4
print('\n', v)
v_round1 = np.around(v,decimals=0)
print('Округленный стандартным методом np.around вектор:\n', v_round1)
v_round2 = np.round(v,decimals=0)
print('Округленный стандартным методом np.round вектор:\n', v_round2)


 [-1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.
  0.25  0.5   0.75  1.    1.25  1.5   1.75]
Округленный стандартным методом np.around вектор:
 [-2. -2. -1. -1. -1. -0. -0.  0.  0.  0.  1.  1.
  1.  2.  2.]
Округленный стандартным методом np.round вектор:
 [-2. -2. -1. -1. -1. -0. -0.  0.  0.  0.  1.  1.
  1.  2.  2.]


In [33]:
v_round_away1 = np.copysign(np.ceil(np.abs(v)), v)
print('Округленный ВВЕРХ вектор первым способом:\n', v_round_away1)
v_round_away2 = np.where(v>0, np.ceil(v), np.floor(v))
print('Округленный ВВЕРХ вектор v вторым способом:\n', v_round_away2)

Округленный ВВЕРХ вектор первым способом:
 [-2. -2. -2. -1. -1. -1. -1.  0.  1.  1.  1.  1.
  2.  2.  2.]
Округленный ВВЕРХ вектор v вторым способом:
 [-2. -2. -2. -1. -1. -1. -1.  0.  1.  1.  1.  1.
  2.  2.  2.]


<h2>30. How to find common values between two arrays?</h2>

In [35]:
v1 = np.random.randint(low=0 , high= 50, size=(20))
print(v1)
v2 = np.random.randint(low=0 , high= 50, size=(20))
print(v2)
print(np.intersect1d(v1, v2))

[ 1 38 38 21 20 35 41 30 24 24 33 33 48 41 49 29
 12 47 18 36]
[ 2 38 40  4 27 34 44 48  8  9 26 39 31 27 29 14
 39 34 38 44]
[29 38 48]


## 31. How to ignore all numpy warnings (not recommended)?

In [36]:
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0

In [37]:
defaults = np.seterr(**defaults)
x = np.ones(1) / 0

/tmp/ipykernel_9619/2394213789.py:2: RuntimeWarning: divide by zero encountered in divide
  x = np.ones(1) / 0


## 32. Is the following expression true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
 ```

In [38]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_9619/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

## 33. How to get the dates of yesterday, today and tomorrow?

In [39]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print('Вчера  :', yesterday)
print('Сегодня:', today)
print('Завтра :',tomorrow)

Вчера  : 2025-01-07
Сегодня: 2025-01-08
Завтра : 2025-01-09


## 34. How to get all the dates corresponding to the month of July 2016?

In [40]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03',
       '2016-07-04', '2016-07-05', '2016-07-06',
       '2016-07-07', '2016-07-08', '2016-07-09',
       '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15',
       '2016-07-16', '2016-07-17', '2016-07-18',
       '2016-07-19', '2016-07-20', '2016-07-21',
       '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27',
       '2016-07-28', '2016-07-29', '2016-07-30',
       '2016-07-31'], dtype='datetime64[D]')

## 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [44]:
x = np.ones(5)*1
print('Исходный вектор x:\n', x)
y = np.ones(5)*4
print('Исходный вектор y:\n', y)
np.add(x,y,out=y)
np.divide(x, 2, out=x)
np.negative(x, out=x)
np.multiply(x, y, out=x)
x

Исходный вектор x:
 [1. 1. 1. 1. 1.]
Исходный вектор y:
 [4. 4. 4. 4. 4.]


array([-2.5, -2.5, -2.5, -2.5, -2.5])

## 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [45]:
x = np.random.uniform(low=0,high=10,size=10)
print('Исходный вектор Z:\n', x)
print('Результат:\n')
print(x // 1)
print(np.floor(x))
print(np.trunc(x))
print(x.astype(int))

Исходный вектор Z:
 [4.1965 2.4481 3.256  6.1755 7.237  7.4834 4.6097
 0.2928 0.3214 9.7353]
Результат:

[4. 2. 3. 6. 7. 7. 4. 0. 0. 9.]
[4. 2. 3. 6. 7. 7. 4. 0. 0. 9.]
[4. 2. 3. 6. 7. 7. 4. 0. 0. 9.]
[4 2 3 6 7 7 4 0 0 9]


## 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [47]:
m = np.zeros((5,5))  
m += np.arange(5)
print('Матрица 5x5 со значениями строк от 0 до 4: \n', m)

Матрица 5x5 со значениями строк от 0 до 4: 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 38. Consider a generator function that generates 10 integers and use it to build an array 

In [48]:
def generate():
    for x in range(8):
        yield x
        
x = np.fromiter(generate(), dtype=int)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

## 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [49]:
x = np.linspace(0,1,11, endpoint=False)[1:]
print('Вектор размера 10 с равномерно распределенными значениями на открытом отрезке (0,1): \n', x)

Вектор размера 10 с равномерно распределенными значениями на открытом отрезке (0,1): 
 [0.0909 0.1818 0.2727 0.3636 0.4545 0.5455 0.6364
 0.7273 0.8182 0.9091]


## 40. Create a random vector of size 10 and sort it

In [58]:
x = np.random.randint(10, size=(1,10))
x.sort()
x

array([[0, 1, 1, 3, 3, 3, 5, 6, 9, 9]])

## 41. How to sum a small array faster than np.sum?

In [69]:
x = np.random.randint(0, 1000, size=1000000)

%time
np.sum(x)

%time
x.sum()

%time 
np.add.reduce(x)

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 4.77 μs
CPU times: user 3 μs, sys: 0 ns, total: 3 μs
Wall time: 5.01 μs
CPU times: user 2 μs, sys: 1e+03 ns, total: 3 μs
Wall time: 4.53 μs


np.int64(499411520)

## 42. Consider two random array A and B, check if they are equal 

In [71]:
%time
x = np.random.randint(0, 2, size=1000000)
y = np.random.randint(0, 2, size=1000000)


np.array_equal(x, y)


CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 4.77 μs


False

## 43. Make an array immutable (read-only) 

In [72]:
x = np.random.randint(0, 2, size=1000000)
x.flags.writeable = False

try:
    x[0] = 1
    print('Значение изменено успешно')
except Exception as e:
    print('Изменение значения невозможно:', e)

Изменение значения невозможно: assignment destination is read-only


## 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [76]:
x = np.random.randint(-1, 2, size=(10, 2)).astype(float64)
r = np.sqrt(x[:,0]**2 + x[:,1]**2)
theta = np.arctan2(x[:,1], x[:,0])
x[:, 0] = r
x[:, 1] = theta
print(x)

[[ 1.4142 -2.3562]
 [ 1.     -1.5708]
 [ 1.      1.5708]
 [ 1.4142 -2.3562]
 [ 1.4142  2.3562]
 [ 1.4142 -0.7854]
 [ 1.4142 -2.3562]
 [ 1.      3.1416]
 [ 0.      0.    ]
 [ 1.      3.1416]]


## 45. Create random vector of size 10 and replace the maximum value by 0 

In [77]:
x = np.random.randint(-1, 10, size=100)

x[x.argmax()] = 0
x

array([ 4,  2,  0,  0, -1,  4,  4, -1,  5,  4,
        5,  5,  1,  1,  5,  6,  5,  6,  2,  2,
        5, -1, -1,  3,  3,  2,  7,  3,  4,  7,
        1,  6,  0,  6,  2, -1,  3,  3, -1,  9,
        4,  0,  7,  3,  0,  4,  3,  2,  2,  6,
        1,  7,  2,  7,  9,  1,  3,  3,  9,  2,
        2,  8,  3,  9,  7,  9, -1,  9,  2,  1,
        1, -1,  4,  7,  5,  0,  0,  3,  5,  2,
        5,  0, -1,  5,  7,  5,  7,  3,  8,  1,
        2,  0,  7, -1,  8,  0,  4,  2,  4,  2])

## 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [78]:
N = 5 
g = np.zeros((N,N), [('x',float),('y',float)])  # зададим массив для координат покрытия области со спец типом
g['x'], g['y'] = np.meshgrid(np.linspace(0,1,num=N),
                             np.linspace(0,1,num=N))
print('Массив с координатами x и y, покрывающими область [0,1] x [0,1]:\n', g)

Массив с координатами x и y, покрывающими область [0,1] x [0,1]:
 [[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  )
  (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25)
  (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 )
  (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75)
  (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  )
  (0.75, 1.  ) (1.  , 1.  )]]


## 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [82]:
x = np.random.randint(0, 10, size=(1,5))
y = np.random.randint(0,10, size=(1, 5))

c = 1.0 / np.subtract.outer(x, y)
c

/tmp/ipykernel_9619/4057597960.py:4: RuntimeWarning: divide by zero encountered in divide
  c = 1.0 / np.subtract.outer(x, y)


array([[[[ 1.    ,     inf, -0.5   , -0.1429,
          -0.125 ]],

        [[ 0.1111,  0.125 ,  0.1667,  1.    ,
              inf]],

        [[ 0.25  ,  0.3333,  1.    , -0.25  ,
          -0.2   ]],

        [[ 0.2   ,  0.25  ,  0.5   , -0.3333,
          -0.25  ]],

        [[    inf, -1.    , -0.3333, -0.125 ,
          -0.1111]]]])

## 48. Print the minimum and maximum representable value for each numpy scalar type

In [83]:
for dtype in [np.int8, np.int32, np.int64]:
   print(f'Тип: {dtype.__name__}, минимум: {np.iinfo(dtype).min}, максимум: {np.iinfo(dtype).max}')
   
for dtype in [np.float32, np.float64]:
   print(f'Тип: {dtype.__name__}, минимум: {np.finfo(dtype).min}, максимум: {np.finfo(dtype).max}, и дельта: {np.finfo(dtype).eps}')

Тип: int8, минимум: -128, максимум: 127
Тип: int32, минимум: -2147483648, максимум: 2147483647
Тип: int64, минимум: -9223372036854775808, максимум: 9223372036854775807
Тип: float32, минимум: -3.4028234663852886e+38, максимум: 3.4028234663852886e+38, и дельта: 1.1920928955078125e-07
Тип: float64, минимум: -1.7976931348623157e+308, максимум: 1.7976931348623157e+308, и дельта: 2.220446049250313e-16


## 49. How to print all the values of an array? 

In [84]:
print('Значение threshold по умолчанию:', np.get_printoptions()['threshold'])
x = np.zeros((20,30))
x

Значение threshold по умолчанию: 1000


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.

In [ ]:
np.set_printoptions(threshold=float("inf"))  # снять ограничения 
np.set_printoptions(threshold=1000) 

## 50. How to find the closest value (to a given scalar) in a vector?

In [85]:
x = np.arange(50)
scalar = 25
np.argmin(np.abs(x - scalar))

np.int64(25)